# Generated by Django 4.2.3 on 2023-07-29 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieAPP', '0002_review_likes_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='likedreviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
