# Generated by Django 4.2.3 on 2023-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieAPP', '0002_favorite_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='moviePost',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
