# Generated by Django 4.2.3 on 2023-07-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieAPP', '0003_alter_favorite_moviepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='movieId',
            field=models.IntegerField(),
        ),
    ]
