# Generated by Django 4.2.3 on 2023-08-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieAPP', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defult.png', null=True, upload_to=''),
        ),
    ]
