# Generated by Django 4.2.3 on 2023-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieAPP', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='noAvatar.png', null=True, upload_to=''),
        ),
    ]
